"""Add options to question_groups

Revision ID: 1aba9e55558c
Revises: 59878757fe65
Create Date: 2026-01-03 23:17:05.867071

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1aba9e55558c"
down_revision: Union[str, Sequence[str], None] = "59878757fe65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("question_groups", sa.Column("options", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question_groups", "options")
    # ### end Alembic commands ###
