"""Add classes and sessions tables for real-time test monitoring

Revision ID: 5cbeb33460e3
Revises: 5cf145a9658b
Create Date: 2026-01-11 22:09:44.134526

Database Design for Fast Writes and Real-Time Monitoring:

1. JSON Columns for Nested Data:
   - classes.student_ids: Array of student IDs (avoids join table, atomic updates)
   - sessions.participants: Array of participant objects with connection state
   - attempts.highlighted_text: Array of text highlights with timestamps

2. Strategic Indexing (read performance without sacrificing write speed):
   - classes: teacher_id, status, name (for filtering active classes)
   - sessions: class_id, status, scheduled_at, created_by, test_id
   - attempts: session_id, student_id, status, test_id (for real-time queries)

3. Minimal Foreign Key Constraints:
   - Only essential FKs to maintain data integrity
   - No cascade deletes that slow down writes

4. Optimized for Real-Time Updates:
   - Single row updates instead of multiple table operations
   - JSON columns allow atomic updates of complex state
   - Indexes on status columns for fast filtering of active sessions
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cbeb33460e3"
down_revision: Union[str, Sequence[str], None] = "5cf145a9658b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classes",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("teacher_id", sa.String(), nullable=False),
        sa.Column("student_ids", sa.JSON(), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "ARCHIVED", name="classstatus"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_classes_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_classes_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_classes_teacher_id"), ["teacher_id"], unique=False
        )

    op.create_table(
        "sessions",
        sa.Column("class_id", sa.String(), nullable=False),
        sa.Column("test_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "WAITING_FOR_STUDENTS",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="sessionstatus",
            ),
            nullable=False,
        ),
        sa.Column("participants", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["tests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sessions_class_id"), ["class_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_created_by"), ["created_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_scheduled_at"), ["scheduled_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_test_id"), ["test_id"], unique=False
        )

    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("session_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("highlighted_text", sa.JSON(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_attempts_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attempts_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attempts_student_id"), ["student_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attempts_test_id"), ["test_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_attempts_session_id", "sessions", ["session_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_attempts_session_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_attempts_test_id"))
        batch_op.drop_index(batch_op.f("ix_attempts_student_id"))
        batch_op.drop_index(batch_op.f("ix_attempts_status"))
        batch_op.drop_index(batch_op.f("ix_attempts_session_id"))
        batch_op.drop_column("highlighted_text")
        batch_op.drop_column("session_id")

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_test_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_status"))
        batch_op.drop_index(batch_op.f("ix_sessions_scheduled_at"))
        batch_op.drop_index(batch_op.f("ix_sessions_created_by"))
        batch_op.drop_index(batch_op.f("ix_sessions_class_id"))

    op.drop_table("sessions")
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_classes_teacher_id"))
        batch_op.drop_index(batch_op.f("ix_classes_status"))
        batch_op.drop_index(batch_op.f("ix_classes_name"))

    op.drop_table("classes")
    # ### end Alembic commands ###
