"""add_is_deleted_column_to_passage_and_test_model

Revision ID: 5cf145a9658b
Revises: 1aba9e55558c
Create Date: 2026-01-06 22:25:19.174495

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cf145a9658b"
down_revision: Union[str, Sequence[str], None] = "1aba9e55558c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("passages", sa.Column("is_deleted", sa.Boolean(), nullable=True))

    # Use batch operations for SQLite compatibility
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.alter_column(
            "question_type",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.Enum(
                "MULTIPLE_CHOICE",
                "TRUE_FALSE_NOTGIVEN",
                "YES_NO_NOTGIVEN",
                "MATCHING_HEADINGS",
                "MATCHING_INFORMATION",
                "MATCHING_FEATURES",
                "MATCHING_SENTENCE_ENDINGS",
                "SENTENCE_COMPLETION",
                "SUMMARY_COMPLETION",
                "NOTE_COMPLETION",
                "TABLE_COMPLETION",
                "FLOW_CHART_COMPLETION",
                "DIAGRAM_LABEL_COMPLETION",
                "SHORT_ANSWER",
                name="questiontype",
            ),
            existing_nullable=False,
        )

    op.add_column("tests", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tests", "is_deleted")

    # Use batch operations for SQLite compatibility
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.alter_column(
            "question_type",
            existing_type=sa.Enum(
                "MULTIPLE_CHOICE",
                "TRUE_FALSE_NOTGIVEN",
                "YES_NO_NOTGIVEN",
                "MATCHING_HEADINGS",
                "MATCHING_INFORMATION",
                "MATCHING_FEATURES",
                "MATCHING_SENTENCE_ENDINGS",
                "SENTENCE_COMPLETION",
                "SUMMARY_COMPLETION",
                "NOTE_COMPLETION",
                "TABLE_COMPLETION",
                "FLOW_CHART_COMPLETION",
                "DIAGRAM_LABEL_COMPLETION",
                "SHORT_ANSWER",
                name="questiontype",
            ),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )

    op.drop_column("passages", "is_deleted")
    # ### end Alembic commands ###
