"""fix_timezone_aware_datetime_fields

Revision ID: 5d5adfd19bc5
Revises: 949fce0add24
Create Date: 2025-12-28 00:25:54.463189

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d5adfd19bc5"
down_revision: Union[str, Sequence[str], None] = "949fce0add24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
