"""Add question_groups table and update QuestionType enum

Revision ID: 7d8ec5f13c61
Revises: 5d5adfd19bc5
Create Date: 2025-12-31 16:55:45.545915

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d8ec5f13c61"
down_revision: Union[str, Sequence[str], None] = "5d5adfd19bc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_groups",
        sa.Column("passage_id", sa.String(), nullable=False),
        sa.Column("group_instructions", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "MULTIPLE_CHOICE",
                "TRUE_FALSE_NOT_GIVEN",
                "YES_NO_NOT_GIVEN",
                "MATCHING_HEADINGS",
                "MATCHING_INFORMATION",
                "MATCHING_FEATURES",
                "MATCHING_SENTENCE_ENDINGS",
                "SENTENCE_COMPLETION",
                "SUMMARY_COMPLETION",
                "NOTE_COMPLETION",
                "TABLE_COMPLETION",
                "FLOW_CHART_COMPLETION",
                "DIAGRAM_LABEL_COMPLETION",
                "SHORT_ANSWER",
                name="questiontype",
            ),
            nullable=False,
        ),
        sa.Column("start_question_number", sa.Integer(), nullable=False),
        sa.Column("end_question_number", sa.Integer(), nullable=False),
        sa.Column("order_in_passage", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["passages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Use batch_alter_table for SQLite compatibility
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("question_group_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("instructions", sa.Text(), nullable=True))

    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_questions_question_group_id",
            "question_groups",
            ["question_group_id"],
            ["id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_constraint("fk_questions_question_group_id", type_="foreignkey")
        batch_op.drop_column("instructions")
        batch_op.drop_column("question_group_id")

    op.drop_table("question_groups")
    # ### end Alembic commands ###
